### ISSUE TITLE
Ensembles - Error in merge: Error Domain=CDEErrorDomain Code=201 “(null)” ?

### ISSUE THREAD

**Issue by johnheb** [nengo/nengo_1.4#434]
Trying to get Ensembles working using a device and multiple simulator sessions. Initial Sync works perfectly. After that, very random sync between devices. Verbose shows activity without errors except for this one: Error Domain=CDEErrorDomain Code=201 "(null)" Preceded by ...Integrating New events into main context and baseline has changed will carry out full integration of persistent store.  Does anyone know what this error means and how to fix it?

**Comment by tbekolay** [comment]
By Ensembles are you referring to https://github.com/drewmccormack/ensembles? Nengo isn't related to that project at all, Nengo 1.4 is a Java-based neural networks simulator. There's no syncing and I don't believe we can raise a CDEError.

**Comment by johnheb** [comment]
Wrong group
